"""Initial migration

Revision ID: 6efb60fe1215
Revises: 
Create Date: 2026-05-04 14:06:56.919893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efb60fe1215'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('external_id')
    )
    op.create_table('groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('notification_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('contact_methods',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('channel', sa.Enum('sms', 'email', 'telegram', name='channel_type'), nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_methods_contact_id'), 'contact_methods', ['contact_id'], unique=False)
    op.create_table('group_contacts',
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('group_id', 'contact_id')
    )
    op.create_table('notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'in_progress', 'success', 'partial_success', 'failed', name='notification_status'), server_default='pending', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_group_id'), 'notifications', ['group_id'], unique=False)
    op.create_index(op.f('ix_notifications_template_id'), 'notifications', ['template_id'], unique=False)
    op.create_table('deliveries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('notification_id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('contact_method_id', sa.Integer(), nullable=False),
        sa.Column('channel', sa.Enum('sms', 'email', 'telegram', name='channel_type'), nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='delivery_status'), server_default='pending', nullable=False),
        sa.Column('provider_message_id', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_method_id'], ['contact_methods.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_contact_id'), 'deliveries', ['contact_id'], unique=False)
    op.create_index(op.f('ix_deliveries_contact_method_id'), 'deliveries', ['contact_method_id'], unique=False)
    op.create_index(op.f('ix_deliveries_notification_id'), 'deliveries', ['notification_id'], unique=False)
    op.create_index('ix_delivery_notification_status', 'deliveries', ['notification_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delivery_notification_status', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_notification_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_contact_method_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_contact_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_notifications_template_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_group_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('group_contacts')
    op.drop_index(op.f('ix_contact_methods_contact_id'), table_name='contact_methods')
    op.drop_table('contact_methods')
    op.drop_table('notification_templates')
    op.drop_table('groups')
    op.drop_table('contacts')
    # ### end Alembic commands ###
